AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnvName:
    Type: String
Mappings:
  EnvMap:
    dev:
       # TODO: KMS指定
      EncryptionKey: '(KMSキー)'
      ApiCertificateArn: 'arn:aws:acm:ap-northeast-1:(アカウントID):certificate/(???)'
      ApiDomainName: 'sample.com'
      ApiHostedZoneId: ''
      BranchName: 'dev'
Resources:
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub 'sample-api-${EnvName}'
      ArtifactStore:
        Type: S3
        Location: !Sub 'artifacts-${EnvName}'
        EncryptionKey:
          Id:
            Fn::FindInMap:
              - EnvMap
              - Ref: EnvName
              - EncryptionKey
          Type: KMS
      RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/codepipeline-role
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              RunOrder: 1
              Configuration:
                PollForSourceChanges: false
                RepositoryName: 'sample'
                BranchName:
                  Fn::FindInMap:
                    - EnvMap
                    - Ref: EnvName
                    - BranchName
              InputArtifacts: []
              OutputArtifacts:
                - Name: SourceArtifact
              RoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/codecommit-role # TODO: マルチアカウント対応の際は要修正が必要
#              RoleArn: !Sub arn:aws:iam::相手先のアカウントIDを指定:role/codecommit-role # TODO: マルチアカウント対応の際は要修正が必要
        - Name: Deploy
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: 1
              RunOrder: 1
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              RunOrder: 2
              Configuration:
                ProjectName: !Ref 'CodeBuild'
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
  CodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub 'sample-api-${EnvName}'
      BadgeEnabled: false
      ServiceRole: !Sub arn:aws:iam::${AWS::AccountId}:role/codebuild-role # TODO: codebuildロール
      TimeoutInMinutes: 60
      Artifacts:
        Type: CODEPIPELINE
      EncryptionKey:
        Fn::FindInMap:
          - EnvMap
          - Ref: EnvName
          - EncryptionKey
      Source:
        Type: CODEPIPELINE
        BuildSpec: 'buildspec_api.yaml'
      Environment:
        Image: 'aws/codebuild/amazonlinux2-x86_64-standard:3.0'
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_MEDIUM
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: ENV_NAME
            Value: !Ref 'EnvName'
            Type: PLAINTEXT
          - Name: S3_BUCKET
            Value: !Sub 'sample-sam-deployment-${EnvName}'
            Type: PLAINTEXT
          - Name: API_CERTIFICATE_ARN
            Value:
              Fn::FindInMap:
                - EnvMap
                - Ref: EnvName
                - ApiCertificateArn
            Type: PLAINTEXT
          - Name: API_DOMAIN_NAME
            Value:
              Fn::FindInMap:
                - EnvMap
                - Ref: EnvName
                - ApiDomainName
            Type: PLAINTEXT
          - Name: API_HOSTED_ZONE_ID
            Value:
              Fn::FindInMap:
                - EnvMap
                - Ref: EnvName
                - ApiHostedZoneId
            Type: PLAINTEXT