AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  EnvName:
    Type: String
Resources:
  SampleTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: !Sub "sample-${EnvName}"
      AttributeDefinitions:
      - AttributeName: "id"
        AttributeType: "S"
      - AttributeName: "name"
        AttributeType: "S"
      KeySchema:
      - AttributeName: "id"
        KeyType: "HASH"
      - AttributeName: "name"
        KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true